stages:
  - test

cache:
  paths:
   - node_modules/

test-8:
  image: node:8
  stage: test
  before_script:
    - apt update && apt upgrade -y && apt install -y --no-install-recommends cmake g++ git libfontconfig1-dev libfreetype6-dev make python
    - npm prune
    - npm install
    - npm run build
  script:
    - npm test

test-10:
  image: node:10
  stage: test
  before_script:
    - apt update && apt upgrade -y && apt install -y --no-install-recommends cmake g++ git libfontconfig1-dev libfreetype6-dev make python
    - npm prune
    - npm install
    - npm run build
  script:
    - npm test

test-12:
  image: node:12
  stage: test
  before_script:
    - apt update && apt upgrade -y && apt install -y --no-install-recommends cmake g++ git libfontconfig1-dev libfreetype6-dev make python
    - npm prune
    - npm install
    - npm run build
  script:
    - npm test
